
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 14 11:03:07 CST 2019
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int error = 1;
  public static final int T_TRUNCATE = 3;
  public static final int T_TABLE = 2;
  public static final int EOF = 0;
  public static final int T_IDENTIFICADOR = 4;
}

