/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package analizador;

/**
 *
 * @author Carlos
 */
public enum Token {
    T_WHITE, T_ENTER, T_ENTERODECIMAL, T_ENTEROHEX, T_CONSTBOOL,T_STRINGA,  T_COMENTARIOS,
    T_COMENTARIOS2,T_ERRORCOMENTARIOS, T_OPSUMA,T_OPRESTA,T_OPMULTI, T_OPDIV, T_OPPORCENTAJE,   
    T_OPMENORQUE,T_OPMENORIGUAL, T_OPMAYORQUE,T_OPMAYORIGUAL, T_IGUAL, T_OPDOBLEIGUAL,T_OPDIFERENTE,
    T_OPAND,T_OPOR, T_OPADMIRACION,T_OPPUNTOCOMA,T_OPCOMA,T_OPPUNTO,T_OPBRACKETIZQ, T_OPBRACKETDER,
    T_OPPARENTESISIZQ,T_OPPARENTESISDER,T_OPCORCHETEIZQ,T_OPCORCHETEDER,T_OPBRACKETS,T_OPPARENTESIS,
    T_OPCORCHETES,T_ARROBA,T_NUMERAL,T_DOBLENUMERAL,T_DOUBLENUM,T_ADD,T_ALL,T_ALTER,T_AND,T_ANY, T_AS,
    T_ASC, T_AUTHORIZATION,T_BACKUP,T_BEGIN,T_BETWEEN,T_BREAK,T_BROWSE,T_BULK,T_BY,T_CASCADE,T_CASE,
    T_CHECK,T_CHECKPOINT,T_CLOSE,T_CLUSTERED,T_COALESCE,T_COLLATE,T_COLUMN,T_COMMIT,T_COMPUTE,T_CONSTRAINT,
    T_CONTAINS,T_CONTAINSTABLE,T_CONTINUE,T_CONVERT,T_CREATE,T_CROSS,T_CURRENT,T_CURRENT_DATE,T_CURRENT_TIME,
    T_CURRENT_TIMESTAMP,T_CURRENT_USER,T_CURSOR,T_DATABASE,T_DBCC,T_DEALLOCATE,T_DECLARE,T_DEFAULT,T_DELETE,
    T_DENY,T_DESC,T_DISK,T_DISTINCT,T_DISTRIBUTED,T_DOUBLE,T_DROP,T_DUMP,T_ELSE,T_END,T_ERRLVL,T_ESCAPE,
    T_EXCEPT, T_EXEC,T_EXECUTE,T_EXISTS,T_EXIT,T_EXTERNAL,T_FETCH,T_FILE,T_FILLFACTOR,T_FOR,T_FOREIGN,T_FREETEXT,
    T_FREETEXTTABLE,T_FROM,T_FULL,T_FUNCTION,T_GOTO,T_GRANT,T_GROUP,T_HAVING,T_HOLDLOCK,T_IDENTITY,T_IDENTITY_INSERT,
    T_IDENTITYCOL,T_IF,T_IN,T_INDEX,T_INNER,T_INSERT,T_INTERSECT,T_INTO,T_IS,T_JOIN,T_KEY,T_KILL,T_LEFT,T_LIKE,T_LINENO,
    T_LOAD,T_MERGE,T_NATIONAL,T_NOCHECK,T_NONCLUSTERED,T_NOT, T_NULL,T_NULLIF,T_OF,T_OFF,T_OFFSETS,T_ON,T_OPEN,T_OPENDATASOURCE,
    T_OPENQUERY, T_OPENROWSET,T_OPENXML,T_OPTION,T_OR,T_ORDER,T_OUTER,T_OVER,T_PERCENT,T_PIVOT,T_PLAN,T_PRECISION,T_PRIMARY,
    T_PRINT,T_PROC,T_PROCEDURE,T_PUBLIC,T_RAISERROR,T_READ,T_READTEXT,T_RECONFIGURE,T_REFERENCES,T_REPLICATION,
    T_RESTORE,T_RESTRICT,T_RETURN,T_REVERT,T_REVOKE,T_RIGHT,T_ROLLBACK,T_ROWCOUNT,T_ROWGUIDCOL,T_RULE,T_SAVE,T_SCHEMA,
    T_SECURITYAUDIT,T_SELECT,T_SEMANTICKEYPHRASETABLE,T_SEMANTICSIMILARITYDETAILSTABLE,T_SEMANTICSIMILARITYTABLE,
    T_SESSION_USER,T_SET,T_SETUSER,T_SHUTDOWN,T_SOME,T_STATISTICS,T_SYSTEM_USER,T_TABLE,T_TABLESAMPLE,T_TEXTSIZE,T_THEN,
    T_TO,T_TOP,T_TRAN,T_TRANSACTION,T_TRIGGER,T_TRUNCATE,T_TRY_CONVERT,T_TSEQUAL,T_UNION,T_UNIQUE,T_UNPIVOT,T_UPDATE,
    T_UPDATETEXT,T_USE,T_USER,T_VALUES,T_VARYING,T_VIEW,T_WAITFOR,T_WHEN,T_WHERE,T_WHILE,T_WITH,T_WITHIN_GROUP,T_WRITETEXT,
    T_IDENTIFICADOR, ERROR,T_ABSOLUTE,T_ACTION, T_ADA, T_ALLOCATE, T_ARE, T_ASSERTION, T_AT,
T_AVG, T_BIT, T_BIT_LENGTH,  T_BOTH, T_CASCADED, T_CAST, T_CATALOG,T_CHAR,T_CHAR_LENGTH,
T_CHARACTER, T_CHARACTER_LENGTH, T_COLLATION, T_CONNECT,T_CONNECTION,T_CONSTRAINTS,T_CORRESPONDING, T_COUNT, T_DATE, T_DAY, T_DEC, T_DECIMAL,
T_DEFERRABLE,T_DEFERRED, T_DESCRIBE, T_DESCRIPTOR, 
T_DIAGNOSTICS, T_DISCONNECT, T_DOMAIN, T_END_EXEC, T_EXCEPTION, T_EXTRACT, T_FALSE, T_FIRST, T_FLOAT,
T_FORTRAN, T_FOUND, T_GET, T_GLOBAL, T_GO, T_HOUR, T_IMMEDIATE, T_INCLUDE, T_INDICATOR, T_INITIALLY,
T_INPUT, T_INSENSITIVE, T_INT, T_INTEGER, T_INTERVAL, T_ISOLATION, T_LANGUAGE, T_LAST, T_LEADING, T_LEVEL, T_LOCAL,
T_LOWER, T_MATCH, T_MAX, T_MIN, T_MINUTE, T_MODULE, T_MONTH, T_NAMES, T_NATURAL, T_NCHAR, T_NEXT, T_NO,
T_NONE, T_NUMERIC, T_OCTET_LENGTH, T_ONLY, T_OUTPUT, T_OVERLAPS, T_PAD, T_PARTIAL, T_PASCAL, T_POSITION,
T_PREPARE, T_PRESERVE, T_PRIOR, T_PRIVILEGES, T_REAL, T_RELATIVE, T_ROWS, T_SCROLL, T_SECOND, T_SECTION,
T_SESSION, T_SIZE, T_SMALLINT, T_SPACE, T_SQL, T_SQLCA, T_SQLCODE, T_SQLERROR, T_SQLSTATE,
T_SQLWARNING, T_SUBSTRING, T_SUM, T_TEMPORARY, T_TIME, T_TIMESTAMP,
T_TIMEZONE_HOUR, T_TIMEZONE_MINUTE, T_TRAILING, T_TRANSLATE, T_TRANSLATION, T_TRIM, T_TRUE, T_UNKNOWN,
T_UPPER, T_USAGE, T_USING, T_VALUE, T_VARCHAR, T_WHENEVER, T_WORK, T_WRITE, T_YEAR, T_ZONE
  
    
}
